played around with docker

diff --git a/web-service/Dockerfile.web-service b/web-service/Dockerfile.web-service
--- a/web-service/Dockerfile.web-service
+++ b/web-service/Dockerfile.web-service
@@ -1,9 +1,28 @@
+# This is the PHP image for production, it contains a single php-fpm binary
+# with most extensions statically compiled in. This image does not contain a
+# CLI version of PHP, or any other programs. Its sole purpose is to run php-fpm
+# and nothing else, this is in perfect accordance with the slim container
+# approach.
+#
+# TODO provide an alternative image that has a CLI and debugging capabilities
+
 FROM debian:stretch-slim
 
-ENTRYPOINT ["/usr/local/sbin/php-fpm"]
-CMD ["-y", "/usr/local/etc/php/fpm.ini"]
+ENTRYPOINT ["/usr/local/sbin/php-fpm", "-y", "/usr/local/etc/php/fpm.ini"]
 STOPSIGNAL SIGQUIT
 WORKDIR /srv/www
+
+# As it stands right now both extensions are broken. Trying to compile them as
+# static extensions with added security fails and reveals various problems. A
+# typical C problem. There is another problem with the Protobuf extension, it
+# supports only Protobuf 3, whereas most of our stuff is Protobuf 2. It seems
+# as if we have to rely on pure PHP implementations for now. :(
+#
+# TODO contribute fixes to both gRPC and Protobuf
+# - https://github.com/google/protobuf/issues?q=is%3Aissue+is%3Aopen+label%3Aphp
+# - https://github.com/grpc/grpc/issues?q=is%3Aissue+is%3Aopen+label%3Alang%2Fphp
+ARG BUILD_GRPC=false
+ARG BUILD_PROTOBUF=false
 
 ENV DEBIAN_FRONTEND="teletype" LANG="C.UTF-8" \
 	TRV_HSW_SERVICE_PHP_OPCACHE_TTL=86400 \
@@ -11,51 +30,86 @@ ENV DEBIAN_FRONTEND="teletype" LANG="C.UTF-8" \
 
 COPY resources/vendor-keys.pub /usr/local/src/vendor-keys.pub
 
-RUN \
-set -exu;\
-\
-readonly PHP_VERSION=7.1.7;\
-readonly PHP_DIGEST=0d42089729be7b2bb0308cbe189c2782f9cb4b07078c8a235495be5874fff729;\
-readonly GRPC_VERSION=v1.4.x;\
-readonly BUILD_DEPS='build-essential ca-certificates curl file gnupg re2c';\
-\
+RUN set -exu;\
+#
+# ------------------------------------------------------------------------------ Config
+#
+# PHP version to compile (`major.minor.patch`)
+readonly PHP_VERSION='7.1.7';\
+#
+# SHA256 digest of the PHP `.tar.xz` archive
+readonly PHP_DIGEST='0d42089729be7b2bb0308cbe189c2782f9cb4b07078c8a235495be5874fff729';\
+#
+# https://github.com/grpc/grpc/tags
+readonly PHP_GRPC_VERSION='v1.4.1';\
+#
+# https://github.com/google/protobuf/tags
+readonly PHP_PROTOBUF_VERSION='v3.3.2';\
+#
+# Dependencies required for building (not part of the final image)
+readonly BUILD_DEPS='autoconf automake build-essential ca-certificates curl file git gnupg libtool re2c';\
+#
+# ------------------------------------------------------------------------------
+#
+info() { printf '\n\033[33m%s\033[0m\n\n' "$1"; };\
+apt_update() { apt-get update -qq; };\
+apt_install() { apt-get install -qqy --auto-remove --no-install-recommends --no-install-suggests $*; };\
+php_extensions=;\
+add_php_ext() { php_extensions="${php_extensiions} --${1}"; };\
+#
 mkdir -p /etc/dpkg/dpkg.conf.d;\
-echo 'path-exclude /usr/share/doc-base/*' > /etc/dpkg/dpkg.conf.d/01_nodoc;\
-echo 'path-exclude /usr/share/doc/*' >> /etc/dpkg/dpkg.conf.d/01_nodoc;\
-echo 'path-exclude /usr/share/groff/*' >> /etc/dpkg/dpkg.conf.d/01_nodoc;\
-echo 'path-exclude /usr/share/info/*' >> /etc/dpkg/dpkg.conf.d/01_nodoc;\
-echo 'path-exclude /usr/share/linda/*' >> /etc/dpkg/dpkg.conf.d/01_nodoc;\
-echo 'path-exclude /usr/share/lintian/*' >> /etc/dpkg/dpkg.conf.d/01_nodoc;\
-echo 'path-exclude /usr/share/man/*' >> /etc/dpkg/dpkg.conf.d/01_nodoc;\
-\
+touch /etc/dpkg/dpkg.conf.d/01_nodoc;\
+for e in 'doc-base doc groff info linda lintian man';\
+	do echo "path-exclude /usr/share/${e}/*" >> /etc/dpkg/dpkg.conf.d/01_nodoc;\
+done;\
+#
 cd /usr/local/src;\
-apt-get update -q;\
-apt-get install -qy --auto-remove --no-install-recommends --no-install-suggests ${BUILD_DEPS};\
-\
+#
+info 'installing build dependencies';\
+apt_update;\
+apt_install ${BUILD_DEPS};\
+#
+info 'importing vendor GPG keys';\
 gpg --import vendor-keys.pub;\
-rm /usr/local/src/vendor-keys.pub;\
-\
-cd /usr/local/src;\
+#
+info 'downloading PHP sources and verifying their authenticity';\
 curl -sLSo php.tar.xz https://secure.php.net/get/php-${PHP_VERSION}.tar.xz/from/this/mirror;\
 echo "${PHP_DIGEST} *php.tar.xz" | sha256sum -c -;\
 curl -sLSo php.tar.xz.asc https://secure.php.net/get/php-${PHP_VERSION}.tar.xz.asc/from/this/mirror;\
 gpg --batch --verify php.tar.xz.asc php.tar.xz;\
 tar -xJf php.tar.xz;\
 mv php-${PHP_VERSION} php;\
-\
-cd /usr/local/src/php;\
+#
+if [ ${BUILD_PROTOBUF} = true ]; then\
+	info "downloading PHP Protobuf extension ${PHP_PROTOBUF_VERSION}";\
+	git clone -qb ${PHP_PROTOBUF_VERSION} --depth 1 https://github.com/google/protobuf.git;\
+	mv protobuf/php/ext/google/protobuf php/ext/protobuf;\
+	add_php_ext with-protobuf;\
+fi;\
+#
+if [ ${BUILD_GRPC} = true ]; then\
+	info "downloading PHP gRPC extension ${PHP_GRPC_VERSION}";\
+	git clone -qb ${PHP_GRPC_VERSION} --jobs 8 --recurse-submodules https://github.com/grpc/grpc.git;\
+	cd grpc;\
+	make -s;\
+	make install;\
+	ldconfig;\
+	cd ..;\
+	mv grpc/src/php/ext/grpc php/ext/grpc;\
+	add_php_ext with-grpc;\
+fi;\
+#
+info "building and installing php-fpm ${PHP_VERSION}";\
+cd php;\
 adduser --system --group --disabled-password --disabled-login --no-create-home php;\
-\
-export CFLAGS='-D_FORTIFY_SOURCE=2 -fstack-protector-strong -fpic -fpie -O2 -pipe -Wformat -Wformat-security';\
-export PHP_CPPFLAGS="${CFLAGS}";\
-export LDFLAGS='-Wl,-O1 -Wl,--hash-style,gnu -Wl,-z,relro -Wl,-z,now';\
+./buildconf --force;\
 ./configure \
 --build="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \
 --with-config-file-path=/usr/local/etc/php \
 --with-config-file-scan-dir=/usr/local/etc/php/fpm-enabled \
 --with-libdir="lib/$(dpkg-architecture --query DEB_BUILD_MULTIARCH)" \
 --with-pic \
-\
+#
 --disable-cgi \
 --disable-cli \
 --disable-phpdbg \
@@ -67,44 +121,35 @@ export LDFLAGS='-Wl,-O1 -Wl,--hash-style,gnu -Wl,-z,relro -Wl,-z,now';\
 --enable-libgcc \
 --enable-re2c-cgoto \
 --enable-static \
-\
+#
 --with-fpm-user=php \
 --with-fpm-group=php \
-\
+#
 --disable-all \
+#
 --enable-json \
 --enable-mbstring \
 --enable-mysqlnd \
 --enable-opcache \
 --with-mysqli=mysqlnd \
---with-pear \
 --with-pcre-jit \
 --with-pcre-regex \
-;\
+${php_extensions};\
+#
+export CFLAGS='-D_FORTIFY_SOURCE=2 -fstack-protector-strong -fpic -fpie -O2 -pipe -Wformat -Wformat-security';\
+export PHP_CPPFLAGS="${CFLAGS}";\
+export LDFLAGS='-Wl,-O1 -Wl,--hash-style,gnu -Wl,-z,relro -Wl,-z,now';\
 make -sj`nproc`;\
 make install;\
 strip --strip-all /usr/local/sbin/php-fpm;\
-\
+#
 mkdir -p /var/log/php;\
 ln -sf /dev/stdout /var/log/php/access.log;\
 ln -sf /dev/stderr /var/log/php/error.log;\
-\
-which pear || true;\
-\
-#cd /usr/local/src;\
-#git clone -b "${GRPC_VERSION}" https://github.com/grpc/grpc;\
-#cd grpc;\
-#git pull --recurse-submodules;\
-#git submodule update --init --recursive;\
-#make -sj`nproc`;\
-#cd grpc/src/php/ext/grpc;\
-#phpize;\
-#./configure;\
-#make -sj`nproc`;\
-#make install;\
-\
-apt-get purge -qy --auto-remove ${BUILD_DEPS};\
-apt-get clean -qy;\
+#
+info 'cleanup';\
+apt-get purge -qqy --auto-remove ${BUILD_DEPS};\
+apt-get clean -qqy;\
 rm -rf \
 /etc/dpkg/dpkg.conf.d/ \
 /root/.gnupg/ \
@@ -124,5 +169,6 @@ rm -rf \
 /usr/share/man/ \
 /var/lib/apt/lists/* \
 /var/tmp/*;\
-\
+#
+printf '\n\033[32mfinished\033[0m\n\n';\
 php-fpm -v
